In [1]:
import pandas as pd #数据分析
import numpy as np #科学计算
from pandas import Series,DataFrame

Get the current Axes:<br> https://matplotlib.org/api/_as_gen/matplotlib.pyplot.gca.html

https://stackoverflow.com/questions/2051744/reverse-y-axis-in-pyplot

### Model Ensemble

模型融合可以比较好地缓解，训练过程中产生的过拟合问题，从而对于结果的准确度提升有一定的帮助

In [13]:
train_df = pd.read_csv('data_for_ensemble_model.csv',index_col=0)
train_df = train_df.set_index('PassengerId')
train_df.head()

Survived  SibSp  Parch  Cabin_No  Cabin_Yes  Embarked_C  \
PassengerId                                                            
1                   0      1      0         1          0           0   
2                   1      1      0         0          1           1   
3                   1      0      0         1          0           0   
4                   1      1      0         0          1           0   
5                   0      0      0         1          0           0   

             Embarked_Q  Embarked_S  Sex_female  Sex_male     ...       \
PassengerId                                                   ...        
1                     0           1           0         1     ...        
2                     0           0           1         0     ...        
3                     0           1           1         0     ...        
4                     0           1           1         0     ...        
5                     0           1           0         1     ...        

             Pclass_2  Pclass_3  Sex_Pclass_female_1  Sex_Pclass_female_2  \
PassengerId                                                                 
1                   0         1                    0                    0   
2                   0         0                    1                    0   
3                   0         1                    0                    0   
4                   0         0                    1                    0   
5                   0         1                    0                    0   

             Sex_Pclass_female_3  Sex_Pclass_male_1  Sex_Pclass_male_2  \
PassengerId                                                              
1                              0                  0                  0   
2                              0                  0                  0   
3                              1                  0                  0   
4                              0                  0                  0   
5                              0                  0                  0   

             Sex_Pclass_male_3  Age_scaled  Fare_scaled  
PassengerId                                              
1                            1   -0.561380    -0.502445  
2                            0    0.613171     0.786845  
3                            0   -0.267742    -0.488854  
4                            0    0.392942     0.420730  
5                            1    0.392942    -0.486337  

[5 rows x 21 columns]

### Model Ensemble 1.1 Bagging

In [14]:
from sklearn.ensemble import BaggingRegressor
from sklearn import linear_model

train_df = train_df.filter(regex='Survived|Age_.*|SibSp|Parch|Fare_.*|Cabin_.*|Embarked_.*|Sex_.*|Pclass.*|Mother|Child|Family|Title')
train_np = train_df.values

# y即Survival结果
y = train_np[:, 0]

# X即特征属性值
X = train_np[:, 1:]

clf = linear_model.LogisticRegression(C=1.0, penalty='l1', tol=1e-6)
# fit到BaggingRegressor之中
# 注意，这里是regressor，用0，1进行回归拟合，结果不好
bagging_reg = BaggingRegressor(clf, n_estimators=20, max_samples=0.8, max_features=1.0, bootstrap=True, bootstrap_features=False, n_jobs=-1)
bagging_reg.fit(X, y)

BaggingRegressor(base_estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l1', random_state=None, solver='liblinear', tol=1e-06,
          verbose=0, warm_start=False),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=0.8, n_estimators=20, n_jobs=-1, oob_score=False,
         random_state=None, verbose=0, warm_start=False)

In [22]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(bagging_clf, X, y, cv=5)
scores

array([0.2463291 , 0.25668329, 0.30093405, 0.19145506, 0.44714355])

In [26]:
from sklearn.ensemble import BaggingClassifier
bagging_clf = BaggingClassifier(clf, n_estimators=20, max_samples=0.8, max_features=1.0, bootstrap=True, bootstrap_features=False, n_jobs=-1)
bagging_clf.fit(X, y)
scores = cross_val_score(bagging_clf, X, y, cv=5)
scores

array([0.77094972, 0.78212291, 0.82022472, 0.80337079, 0.83615819])

###  Model Ensemble 1.2 Random Forest

In [27]:
from sklearn.ensemble import RandomForestClassifier
# fit到RandomForestRegressor之中
forest = RandomForestClassifier(n_estimators=100,
                                criterion='gini',
                                max_depth=5,
                                min_samples_split=10,
                                min_samples_leaf=5,
                                random_state=0)
forest.fit(X, y)
forest

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=5, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=10,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [163]:
### cross validation

In [29]:
scores = cross_validation.cross_val_score(forest,X,y,scoring='accuracy',cv=5)
scores

array([0.80446927, 0.81005587, 0.81460674, 0.79213483, 0.81355932])

### Model Ensemble 1.3 SVM

In [170]:
from sklearn.svm import SVC
train_df = pd.read_csv("processed_dataset.csv")
train_df.drop("PassengerId", axis=1, inplace=True)
# Age_.* means any fields begin with Age
train_df = df.filter(regex='Survived|Age_.*|SibSp|Parch|Fare_.*|Cabin_.*|Embarked_.*|Sex_.*|Pclass_.*')
train_np = train_df.values

# y即Survival结果
y = train_np[:, 0]

# X即特征属性值
X = train_np[:, 1:]

# fit
svm = SVC()
svm.fit(X, y)
svm

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [178]:
scores = cross_validation.cross_val_score(svm,x,y,scoring='accuracy',cv=5)
scores

array([0.82681564, 0.82122905, 0.81460674, 0.80898876, 0.84180791])

### Model Ensemble 1.4 More models

https://www.kaggle.com/l3r4nd/titanic-prediction-with-svm

In [186]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split, KFold, cross_val_score, GridSearchCV
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, BaggingClassifier, ExtraTreesClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier, plot_importance 
from xgboost import XGBRegressor

In [177]:
train_df = pd.read_csv("processed_dataset.csv")
train_df.drop("PassengerId", axis=1, inplace=True)
# Age_.* means any fields begin with Age
train_df = df.filter(regex='Survived|Age_.*|SibSp|Parch|Fare_.*|Cabin_.*|Embarked_.*|Sex_.*|Pclass_.*')
train_np = train_df.values

# y即Survival结果
y = train_np[:, 0]

# X即特征属性值
X = train_np[:, 1:]

In [189]:
import warnings
warnings.filterwarnings('ignore')

clf_rf = RandomForestClassifier()
clf_et = ExtraTreesClassifier()
clf_bc = BaggingClassifier()
clf_ada = AdaBoostClassifier()
clf_dt = DecisionTreeClassifier()
clf_xg = XGBClassifier()
clf_lr = LogisticRegression()
clf_svm = SVC()

scores = []
models = [clf_rf, clf_et, clf_bc, clf_ada, clf_dt, clf_xg, clf_lr, clf_svm]
for model in models:
    score = cross_val_score(model, x, y, scoring = 'accuracy', cv = 10, n_jobs = -1).mean()
    scores.append(score)
    
Classifiers = ['RandomForest','ExtraTrees','Bagging','AdaBoost','DecisionTree','XGBoost','LogisticRegression','SVM']
mode = pd.DataFrame(scores, index = Classifiers, columns = ['score']).sort_values(by = 'score',
             ascending = False)
mode

score
XGBoost             0.826101
SVM                 0.824927
AdaBoost            0.816064
RandomForest        0.814902
LogisticRegression  0.804715
Bagging             0.803654
ExtraTrees          0.798073
DecisionTree        0.772318

### Model Ensemble 1.5 Ensemble Modeling

https://www.kaggle.com/yassineghouzam/titanic-top-4-with-ensemble-modeling    

### 1.6 Hyperparameter tunning for best models

performed a grid search optimization for XGBoost, SVM , AdaBoost, RandomForest classifiers.

http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.StratifiedKFold.html

In [197]:
from sklearn.model_selection import StratifiedKFold
kfold = StratifiedKFold(n_splits=10)

https://blog.csdn.net/wzmsltw/article/details/50994481

In [208]:
# XGBoost
clf =XGBClassifier(learning_rate=0.1, max_depth=2, 
silent=True, objective='binary:logistic')
# 设置boosting迭代计算次数
param_test = {
    'n_estimators': range(30, 50, 2),
    'max_depth': range(2, 7, 1)
}
grid_search = GridSearchCV(estimator = clf, param_grid = param_test, 
scoring='accuracy', cv=5)
grid_search.fit(x,y)
#grid_search.grid_scores_,
grid_search.best_params_,grid_search.best_score_

({'max_depth': 6, 'n_estimators': 38}, 0.8361391694725028)

In [209]:
XGB = XGBClassifier(learning_rate=0.1)
# 设置boosting迭代计算次数
XGB_param_grid = {'n_estimators': range(30, 50, 2),
                  'max_depth': range(2, 7, 1)}
gsXGB = GridSearchCV(XGB,param_grid = XGB_param_grid,cv=kfold, scoring="accuracy", n_jobs= -1,verbose = 1)
gsXGB.fit(x,y)
XGB_best = gsXGB.best_estimator_
# Best score
gsXGB.best_score_

Fitting 10 folds for each of 50 candidates, totalling 500 fits


[Parallel(n_jobs=-1)]: Done 280 tasks      | elapsed:    3.2s
[Parallel(n_jobs=-1)]: Done 500 out of 500 | elapsed:    6.3s finished


0.8338945005611672

- SVM=Support Vector Machine 是支持向量
- SVC=Support Vector Classification就是支持向量机用于分类，
- SVR=Support Vector Regression.就是支持向量机用于回归分析

<img src='https://pic3.zhimg.com/80/v2-413aa22b468d5bbbaf4b4f2c642f1c9a_hd.jpg'>

### SVM的两个参数 C 和 gamma

- SVM模型有两个非常重要的参数C与gamma。其中 C是惩罚系数，即对误差的宽容度。
- c越高，说明越不能容忍出现误差,容易过拟合。C越小，容易欠拟合。C过大或过小，泛化能力变差
- **gamma是选择RBF函数作为kernel**后，该函数自带的一个参数。隐含地决定了数据映射到新的特征空间后的分布，**gamma越大，支持向量越少**，gamma值越小，支持向量越多。支持向量的个数影响训练与预测的速度。
- 此外大家注意RBF公式里面的sigma和gamma的关系如下：
https://blog.csdn.net/wusecaiyun/article/details/49681431

gamma的物理意义，大家提到很多的RBF的幅宽，它会影响每个支持向量对应的高斯的作用范围，从而影响泛化性能

<img src='https://upload-images.jianshu.io/upload_images/1825662-e9be9419f3fd85bf.png'>

In [200]:
### SVC classifier
SVMC = SVC(probability=True)
svc_param_grid = {'kernel': ['rbf'], 
                  'gamma': [ 0.001, 0.01, 0.1, 1],
                  'C': [1, 10, 50, 100,200,300, 1000]}

gsSVMC = GridSearchCV(SVMC,param_grid = svc_param_grid, cv=kfold, scoring="accuracy", n_jobs= 4, verbose = 1)

gsSVMC.fit(x,y)

SVMC_best = gsSVMC.best_estimator_

# Best score
gsSVMC.best_score_

Fitting 10 folds for each of 28 candidates, totalling 280 fits


[Parallel(n_jobs=4)]: Done  76 tasks      | elapsed:    3.9s
[Parallel(n_jobs=4)]: Done 280 out of 280 | elapsed:   39.0s finished


0.8305274971941639

https://www.cnblogs.com/pinard/p/6136914.html
http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.AdaBoostClassifier.html

In [199]:
#RandomForest
RFC = RandomForestClassifier()


## Search grid for optimal parameters
rf_param_grid = {"max_depth": [None],
              "max_features": [1, 3, 10],
              "min_samples_split": [2, 3, 10],
              "min_samples_leaf": [1, 3, 10],
              "bootstrap": [False],
              "n_estimators" :[100,300],
              "criterion": ["gini"]}


gsRFC = GridSearchCV(RFC,param_grid = rf_param_grid, cv=kfold, scoring="accuracy", n_jobs= -1, verbose = 1)

gsRFC.fit(x,y)

RFC_best = gsRFC.best_estimator_

# Best score
gsRFC.best_score_

Fitting 10 folds for each of 54 candidates, totalling 540 fits


[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:    7.3s
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:   36.4s
[Parallel(n_jobs=-1)]: Done 442 tasks      | elapsed:  1.4min
[Parallel(n_jobs=-1)]: Done 540 out of 540 | elapsed:  1.7min finished


0.8294051627384961

https://www.kaggle.com/l3r4nd/titanic-prediction-with-svm
    多个模型调参数的循环算法

### 1.5.1 Feature importance of tree based classifiers

In order to see the most informative features for the prediction of passengers survival, i displayed the feature importance for the 4 tree based classifiers

https://www.kaggle.com/yassineghouzam/titanic-top-4-with-ensemble-modeling

### 1.5.2 Ensemble Model - Voting

https://www.cnblogs.com/jiaxin359/p/8777574.html

分类的机器学习算法输出有两种类型：
- 一种是直接输出类标签，硬投票(Majority/Hard voting)：比如有4个模型，3个预测得到类1，1个得到类0，则voting得到1.
- 另外一种是输出类概率，叫做软投票(Soft voting)。 sklearn中的VotingClassifier是投票法的实现。

- 如何确定weight：

weighted data。就是把比较难的/容易分错的点的权重提高，简单的点的权重降低。

比如一个点的权重是2，那么可以把它当作两个这个点来看待，那么如果这个点分错了，那么error就是2倍。

In [250]:
from sklearn.ensemble import VotingClassifier
votingC = VotingClassifier(estimators=[("XGBClassifier", XGB_best),("SVM",SVMC_best),("RandomForest",RFC_best)], voting='soft', n_jobs=4)
votingC = votingC.fit(x, y)

In [252]:
scores = cross_validation.cross_val_score(votingC,x,y,scoring='accuracy', cv=10)
print (scores)

[0.77777778 0.82222222 0.74157303 0.88764045 0.92134831 0.82022472
 0.83146067 0.76404494 0.86516854 0.875     ]


## Boosting

基于全部分类器的加权求和结果，而这个权重代表的是该分类器在**上一轮迭代中的成功/正确度**。

但是，这个正确率 =  7/10 + 10/13 + 10/13，和正确答案不一样啊。。

<img src='3.png'>

<img src='322.png'>

### Model Stacking

https://zhuanlan.zhihu.com/p/25836678

模型M1相当于被训练了2次。

<img src='111.png'>

取子集进行训练，可以减少variance，减少过拟合。<br>
然后再把predict的test data的结果Vstack。

- 以上，就得到了**解决过拟合的P1**，然后就可以用P1去训练得到T1了。
- 对于测试集T1的得到，有两种方法。
- 1. 注意到刚刚是2折交叉验证，M1相当于训练了2次，所以一种方法是每一次训练M1，就开始直接对整个test进行预测，这样2折交叉验证后测试集相当于预测了2次，然后对这两列求平均得到T1。
- 2. 或者如上图所示，求完pred并hstack之后，再用M1对测试集进行预测，一次直接得到T1。
- 得到了P1，T1，用其他模型M2，M3等得到的P2，T2，P3，T3也是一样的道理。将P1，2，3进行Hstack，T1，2，3进行Hstack，就可以进行下一层的模型训练了。

所以最终的代码是两层循环，
- 第一层循环控制基模型的数目，每一个基模型要这样去得到P1，T1，
- 第二层循环控制的是交叉验证的次数K，对每一个基模型，会训练K次最后拼接得到P1，用P1对全体test数据进行predict，然后取平均得到T1。

<img src='model stack.gif'>